task:
  name: FreeBSD # https://www.freebsd.org/releases
  freebsd_instance: # https://cirrus-ci.org/guide/FreeBSD/#list-of-available-image-families
    matrix:
      image_family: freebsd-13-2
      image_family: freebsd-14-0
  env:
    IGNORE_OSVERSION: yes # supress package installation error on FreeBSD-13

  install_script:
    - pkg update -f
    - pkg install -y cmake ninja pkgconf gettext nasm gtkmm30 ncurses libcpuid pciutils glfw opencl ocl-icd vulkan-loader vulkan-headers libstatgrab

  build_script:
    - cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DWITH_OPENCL=1
    - cmake --build build
    - cmake --install build

  run_script:
    - sudo CPUX_BCLK=100 cpu-x --issue-fmt
    - cat /tmp/cpu-x.log
    - cat /tmp/cpu-x-daemon.log
