name: AppImage Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  linux-appimage-release:
    name: Linux x64_64 (Release)
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - uses: abbbi/github-actions-tune@v1

    - name: Set environment variables
      run: |
        echo "VERSION=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV
        echo "CHANGELOG_TAG=${GITHUB_REF_NAME//./}---$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Build libcpuid
      run: bash -x ./scripts/build_libcpuid.sh "$BUILD_TYPE"

    - name: Build CPU-X
      run: bash -x ./scripts/build_ubuntu.sh "$BUILD_TYPE" "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Package CPU-X as an AppImage
      run: bash -x ./scripts/build_appimage.sh "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Create versioned release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        artifacts: "AppImage/CPU-X-*.AppImage*"
        body: |
          **Version ${{ env.VERSION }}.**

          [ChangeLog](https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/blob/master/ChangeLog.md#${{ env.CHANGELOG_TAG }})

          ## Packages

          Search the `cpu-x` package in your repositories or [CPU-X on Flathub](https://flathub.org/fr/apps/io.github.thetumultuousunicornofdarkness.cpu-x).

          ## Binary

          - **AppImage**: CPU-X-v${{ env.VERSION }}-x86_64.AppImage (**libfuse2** package is required)

          *Note: a Polkit Authentication agent is mandatory to start daemon from GUI.*

          ## Notes

          ### To packagers
          -

          ### To users
          -
        commit: ${{ github.sha }}
        draft: true
        name: ${{ github.ref_name }}
        prerelease: false
        replacesArtifacts: true
        skipIfReleaseExists: true
        tag: ${{ github.ref_name }}
        token: "${{ secrets.GITHUB_TOKEN }}"
